controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

homepage:
path: /{_locale}
requirements: 
    _locale: '%app_locales%' 
controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
defaults: 
    template: 'default/homepage.html.twig'
    _locale: '%locale%'