<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD4DzPrM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD4DzPrM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD4DzPrM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD4DzPrM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD4DzPrM\App_KernelDevDebugContainer([
    'container.build_hash' => 'D4DzPrM',
    'container.build_id' => '04dea5a6',
    'container.build_time' => 1643734262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD4DzPrM');
