<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEgNCXTx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEgNCXTx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEgNCXTx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEgNCXTx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEgNCXTx\App_KernelDevDebugContainer([
    'container.build_hash' => 'EgNCXTx',
    'container.build_id' => '9dc92f06',
    'container.build_time' => 1643791923,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEgNCXTx');
